import json
import logging
import os
import requests

from datetime import datetime
from django.conf import settings
from PIL import Image
from requests.auth import HTTPBasicAuth

class ArchesAPI:
    """
        Class to manage state for connection to an EAMENA Arches instance.
    """
    logger = logging.getLogger(__name__)

    # Authorisation tokens for the web/api
    oauth_token = None  # Arches authorisation token
    csrf_token = None  # The CSRF token
    eamena_token = None  # Session token generated by the Django server

    # The available endpoints we will be using
    endpoints = {
        # Homepage - Used to request initial session token.
        "index": "index.htm",
        # Used to generate the session token for access
        "log_in": "auth/",
        # Generating/refreshing token for oauth-protected standard endpoints
        "oauth": "o/token/",
        "resource": "resource/",
        "resources": "resources/",
        "add_resource": "add-resource/",
        # Gets a specific resource based (resources/RESOURCE_TYPE/RESOURCE_ID - UUID)
        "get_resource": "resources/%s/%s",  # Gets a specific resource
        "tile": "tile",  # For interacting with tiles to insert data/retrieve IDs
        "search_resources": "search/resources",
        "get_descriptors": "resource/descriptors/",
        "relation": "resource/related/" # For adding related resources
    }

    # Mapping value names from AMAL -> EAMENA Arches values
    node_mapping = {
        "captureDate": "DATE_OF_FILE",
        "url": "FILE_UPLOAD",
        "caption": "DESCRIPTION",
        "latitude": "SPATIAL_COORDINATES_GEOMETRY",
        "longitude": "SPATIAL_COORDINATES_GEOMETRY",
        "image": "FILE_UPLOAD"
    }

    # Mapping value names from EAMENA -> AMAL
    rev_node_mapping = {
        "DATE_OF_FILE": "captureDate",
        "DESCRIPTION": "caption",
        "FILE_UPLOAD": "url",
        "SPATIAL_COORDINATES_GEOMETRY": {"lat", "long"}
    }

    # Nodegroup IDs for insertion groups
    nodegroups = {
        "imagery": "90181f02-5252-11ea-a3f7-02e7594ce0a0",
        "urls": "7f41dcde-518c-11ea-a3f7-02e7594ce0a0",
        "description": "b528b064-5189-11ea-a3f7-02e7594ce0a0",
        "location": "587447d5-b0c2-11ea-9b1f-02e7594ce0a0",
        "file_upload": "c712066a-8094-11ea-a6a6-02e7594ce0a0"
    }

    # Contains the graph_ids, nodegroup ID values, and the fstring/dict for payload formatting
    nodes = {
        "DATE_OF_ACQUISITION": {
            "graph_id": "4077fb00-5253-11ea-a3f7-02e7594ce0a0",
            "nodegroup_id": nodegroups["imagery"],
            "payload": "%s"
        },
        "URL": {
            "graph_id": "7f41dcde-518c-11ea-a3f7-02e7594ce0a0",
            "nodegroup_id": nodegroups["urls"],
            "payload": {"en": {"direction": "ltr", "value": "%s"}}
        },
        "DESCRIPTION": {
            "graph_id": "b528b064-5189-11ea-a3f7-02e7594ce0a0",
            "nodegroup_id": nodegroups["description"],
            "payload": {
                "ar": {"direction": "rtl", "value": "%s"},
                "en": {"direction": "ltr", "value": "%s"},
            }
        },
        "DATE_OF_FILE": {
            "graph_id": "bf22c07c-52f1-11ea-a3f7-02e7594ce0a0",
            "nodegroup_id": nodegroups["imagery"],
            "payload": "%s"
        },
        "SPATIAL_COORDINATES_GEOMETRY": {
            "graph_id": "587447d2-b0c2-11ea-9b1f-02e7594ce0a0",
            "nodegroup_id": nodegroups["location"],
            "payload": {
                "type": "FeatureCollection",
                "features": [{
                    "id": "f8498c82de3c3c3285ed4c24f050a48e",
                    "type": "Feature",
                    "properties": {
                        "nodeId": "587447d2-b0c2-11ea-9b1f-02e7594ce0a0"
                    },
                    "geometry": {
                        "coordinates": [],
                        "type": "Point"
                    }
                }]
            }
        },
        "FILE_UPLOAD": {
            "graph_id": "c712066a-8094-11ea-a6a6-02e7594ce0a0",
            "nodegroup_id": nodegroups["file_upload"],
            "payload": [{
                    "name": "image_1",
                    "accepted": True,
                    "height": 0,
                    "lastModified": 0,
                    "size": 0,
                    "status": "added",
                    "type": "image/jpg",
                    "width": 0,
                    "url": None,
                    "file_id": None,
                    "index": 0,
                    "content": ""
                }]
        }
    }

    # Graph ID values for EAMENA object types
    graphs = {
        "Information Resource": "35b99cb7-379a-11ea-9989-06f597a7d5ce",
        "Built Component": "6c4f0703-c381-11ea-9026-02e7594ce0a0",
        "Detailed Condition Assessment": "f6235ff1-f992-11e9-b345-06f597a7d5ce",
        "Geoarchaeology": "5297fa9e-8e16-11ea-a6a6-02e7594ce0a0",
        "Grid Square": "77d18973-7428-11ea-b4d0-02e7594ce0a0",
        "Heritage Place": "34cfe98e-c2c0-11ea-9026-02e7594ce0a0",
        "Person-Organisation": "e98e1cee-c38b-11ea-9026-02e7594ce0a0"
    }

    def initialise_tokens(self, regenerate=True):
        """
            Initialises the tokens, which also initiates the login function used to
            call for and store the csrf, session and oauth tokens from EAMENA.

            :param regenerate: Bool - Provides option to force regenerate keys
        """
        # If any keys are none, we regen
        if all([self.oauth_token, self.csrf_token, self.eamena_token]) or regenerate:
            self.login()
            self.get_oauth_token()

    def get_endpoint(self, endpoint_id):
        """
        Generates a base URL for a specific endpoint based on a given endpoint ID, and using
        the site URL value.

        :param endpoint_id: str - The endpoint  string identifier to return on
        """
        available_endpoints = self.endpoints.keys()
        if endpoint_id in available_endpoints:
            return f"{settings.EAMENA_TARGET}{self.endpoints[endpoint_id]}"
        else:
            raise ValueError(f"Given endpoint ID string value ({endpoint_id} does not match expected: {available_endpoints}")

    def get_login_data(self):
        """
        Generates a dictionary containing relevant values used for site login.
        Contaisn the csrfmiddlewaretoken, account username and password.

        """
        data = {
            'csrfmiddlewaretoken': self.csrf_token,
            'username': settings.ARCHES_USERNAME,
            'password': settings.ARCHES_PASSWORD
        }
        return data

    def get_headers(self, referrer=None, oauth=False):
        """
            Generates and returns the payload dictionary with required origin, keys and
            session cookies.

            :param referrer: str - Referrer URL string to include as referer
            :param oauth: bool - Whether to include oauth key
        """

        base_headers = {
            'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:139.0) Gecko/20100101 Firefox/139.0',
            'Accept': '*/*',
            'Accept-Language': 'en-GB,en;q=0.5',
            'Accept-Encoding': 'gzip, deflate',
            'X-Requested-With': 'XMLHttpRequest',
            'Connection': 'keep-alive',
            'Origin': f'{settings.EAMENA_TARGET}',
            'Cookie': f'csrftoken={self.csrf_token}; eamena={self.eamena_token};',
            'X-CSRFToken': f'{self.csrf_token}',
            'Priority': 'u=0'
        }

        if referrer:
            base_headers['Referer'] = referrer

        if oauth:
            base_headers["Authorization"] = f"Bearer {self.oauth_token}"

        return base_headers

    def get_oauth_token(self):
        """
            Call for and set the oauth token in this object.
        """
        endpoint = self.get_endpoint("oauth")

        data = {
            "username": settings.ARCHES_USERNAME,
            "password": settings.ARCHES_PASSWORD,
            "grant_type": "password"
        }
        auth = HTTPBasicAuth(
            settings.ARCHES_CLIENT_ID,
            settings.ARCHES_CLIENT_SECRET
        )

        session = requests.Session()
        response_json = session.post(
            endpoint,
            data=data,
            headers=self.get_headers(referrer=endpoint),
            auth=auth
        ).json()

        self.oauth_token = response_json.get("access_token")

    def login(self):
        """
            Logs into the Eamena Arches instance.
            Requests the index page in order to generate a session and csrf token, which are
            saved in this object's variables.

            :returns response: The request's response object.
        """
        response = {
            "status": 0,
            "session": None
        }
        index_endpoint = self.get_endpoint("index")
        session = requests.Session()
        # Request the homepage to begin a session.
        session.get(index_endpoint)

        # Set the Object's internal csrf token for later use
        self.csrf_token = session.cookies.get('csrftoken')

        # Get the pregenerated headers
        headers = self.get_headers(referrer=index_endpoint)

        # Set the data payload to be sent, including csrf token, username and password
        login_data = self.get_login_data()

        login_request = session.post(self.get_endpoint("log_in"), data=login_data, headers=headers)

        if login_request.status_code in [403, 500]:
            self.logger.error(login_request.content.decode('unicode_escape'))

        response["status"] = login_request.status_code
        request_cookies = login_request.request.headers["cookie"]

        self.eamena_token = request_cookies.split("eamena=")[1]
        self.csrf_token = request_cookies.split("csrftoken=")[1].split(";")[0]

    def get_parent_id(self, nodegroup_id, resource_id):
        """
        Makes a request to the Arches instance to determine the resource instance_id value of a given resource object.
        This must be requested
        """
        base_parent_payload = {
            "tileid": "",
            "data": {},
            "nodegroup_id": nodegroup_id,
            "parenttile_id": None,
            "resourceinstance_id": resource_id if resource_id else '',
            "sortorder": 0,
            "tiles": {}
        }

        parent_payload = {
            'data': json.dumps(base_parent_payload, ensure_ascii=False)
        }
        session = requests.Session()
        endpoint = self.get_endpoint("tile")
        parent_request = session.post(endpoint, headers=self.get_headers(referrer=endpoint), data=parent_payload)

        if parent_request.status_code == 200:
            parent_response = json.loads(parent_request.content)
            return parent_response["tileid"]
        else:
            return None

    def upload_image(self, image_data, payload):
        """
        Handles uploading

        :param image_data:
        :param payload: dict - The payload for formatting and insertion
        :returns:
        """

        graph_id = self.nodes["FILE_UPLOAD"]["graph_id"]

        media_split = image_data.split(settings.MEDIA_URL)[-1].lstrip('/')
        full_path = os.path.join(settings.MEDIA_ROOT, media_split)
        file_name = os.path.basename(full_path)

        im = Image.open(full_path)
        file_size_bytes = os.path.getsize(full_path)

        # Load in the base payload from a string
        payload_data = json.loads(payload["data"])
        # Get the image portion of the payload object
        image_payload = payload_data["data"][graph_id][0]
        image_type = f"image/{im.format.lower()}"
        # Insert required values into the payload
        image_payload["size"] = file_size_bytes
        image_payload["name"] = file_name
        image_payload["height"] = im.size[1]
        image_payload["width"] = im.size[0]
        image_payload["lastModified"] = int(datetime.timestamp(datetime.now()))
        payload_data["type"] = image_type

        payload["data"] = json.dumps(payload_data)

        files = {
            f"file-list_{graph_id}": (
                file_name,
                open(full_path, "rb"),
                image_type
            )
        }


        session = requests.Session()
        headers = self.get_headers(referrer=self.get_endpoint("tile"))
        upload_response = session.post(
            self.get_endpoint("tile"),
            headers=headers,
            data=payload,
            files=files
        )

        return upload_response


    def add_payload_data(self, node_name, payload, request_data):
        """
        Adds a given value to a

        :param payload: str/dict -
        :param node_name: str -
        :param request_data:
        """

        node = self.nodes[node_name]["payload"]

        # Coordinates are handled differently
        if node_name == "SPATIAL_COORDINATES_GEOMETRY":
            node["features"][0]["geometry"]["coordinates"] = [request_data["latitude"], request_data["longitude"]]
            value = None
        elif node_name == "FILE_UPLOAD":
            value = None
        else:
            # Otherwise, we just use the reverse node mapping
            value = request_data[self.rev_node_mapping[node_name]]

        dtype = type(node)

        if dtype == str:
            unfinished_string = node
        elif dtype in (list, dict):
            unfinished_string = json.dumps(node)
        else:
            error = f"Payload data must be str, list or dict. Instead got {type(node)}: {node}"
            self.logger.error(error)
            raise ValueError(error)

        # We use % formatting so we can convert dict to str without f
        if value:
            if node_name == "DESCRIPTION":
                formatted_string = unfinished_string % (value, value)
            else:
                formatted_string = unfinished_string % value
        else:
            formatted_string = unfinished_string

        data_value = formatted_string if dtype == str else json.loads(formatted_string)

        graphid = self.nodes[node_name]["graph_id"]
        payload["data"][graphid] = data_value


    def relate_resources(self, image_id, place_id):
        """
        Creates a resource relationship between a Heritage Place object, and a
            Information Resource (Image) object.

        :param image_id: Resource UUID for the Information Resource (image) object
        :param place_id: Resource UUID for the Heritage Place resource object
        :returns status_code: The response status code
        """
        endpoint = self.get_endpoint("relation")
        data = {
            "relationship_properties[datestarted]": "",
            "relationship_properties[dateended]": "",
            "relationship_properties[relationshiptype]": "http://www.cidoc-crm.org/cidoc-crm/BM.PX_is_related_to",
            "relationship_properties[notes]": "",
            "instances_to_relate[]": place_id,
            "root_resourceinstanceid": image_id
        }

        response = requests.post(endpoint, headers=self.get_headers(referrer=endpoint), data=data)
        return response.status_code


    def search_resources(self, request):
        """
        Performs a request to the Arches instance at EAMENA_TARGET to search
        EAMENA resources based on a given set of coordinates (screen boundary).

        :param request: The request object containing coordinate data
        :returns: A dict containing the status code and any hits
        """

        response_dict = {
            "status_code": 0,
            "message": "",
            "data": []
        }
        # Get the coordinates from the request as a list
        coordinates = json.loads(request.body)["coordinates"][0]

        # Building the URL
        url = self.get_endpoint("search_resources")
        map_filter = {
            "type": "FeatureCollection",
            "features": [
                {
                    "type": "Feature",
                    "geometry": {
                        "coordinates": [
                            coordinates
                        ],
                        "type": "Polygon"
                    }
                }
            ]
        }
        url += "?map-filter=" + json.dumps(map_filter)
        resource_filter = f"""&resource-type-filter=[{{"graphid":"{self.graphs["Heritage Place"]}","name":"Heritage Place","inverted":false}}]"""
        url += resource_filter

        response = requests.get(url)

        if response.status_code != 200:
            error_message = f"An error occurred ({response.status_code}): {response.reason}."
            response_dict["message"] = error_message
            self.logger.error(error_message)
            return response_dict
        else:
            response_dict["status_code"] = response.status_code

        result_json = json.loads(response.text)

        try:
            result_hits = result_json["results"]["hits"]["hits"]
        except KeyError as e:
            response_dict["status_code"] = 500
            response_dict["message"] = f"There was a problem with the returned data."
            # Log the error more specifically
            self.logger.error(f"{response_dict['status_code']}: {e} - {response_dict['message']}")
            return response_dict

        for hit in result_hits:
            hit_id = hit["_id"]
            hit_data = hit["_source"]
            hit_coords = hit_data["points"][0]["point"]

            # displaydescription is actually mapped to Resource Summary->Name in Eamena.
            hit_dict = {
                "resource_id": hit_id,
                "resource_name": hit_data["displayname"],
                "resource_type": "Heritage Place",  # What should this actually say for Heritage Place
                "resource_description": hit_data["displaydescription"],
                "coordinates": {
                    "latitude": hit_coords["lat"],
                    "longitude": hit_coords["lon"]
                }
            }

            response_dict["data"].append(hit_dict)
        return response_dict


    @staticmethod
    def validate_image_request(request_data):
        """
            Does some validation on the image upload request payload, then either returns None,
            or a message.

            :param request_data: dict containing the request data values
            :returns: None or a string containing error message
        """
        error = None
        # Determine if any keys are missing.
        key_list = {"id", "latitude", "longitude", "caption", "captureDate", "url", "related_to"}
        used_keys = {item[0] for item in request_data.items()}

        missing_keys = [key for key, value in request_data.items() if value is None]

        if missing_keys or request_data is None:
            error = f"Missing values for key(s): {missing_keys}"

        if key_list != used_keys or len(used_keys) != len(key_list):
            error = f"Incorrect keys used: {used_keys}. Should be {key_list}."

        return error


    def submit_image_report(self, request_data):
        """
        Receives and submits an image to EAMENA from the requqest_data.

        Data in: latitude, longitude, caption, captureDate, image, related_to
        HerBridgeImage:
            id, url, thumbnailUrl
            latitude, longitude, captureDate, caption

        :param request_data:
        :returns:
        """
        resource_id = request_data["id"]

        response_dict = {
            "status_code": 0,
            "content": ""
        }

        validation_error = self.validate_image_request(request_data)

        if validation_error:
            response_dict["message"] = validation_error
            return response_dict

        inserted_parents = {}
        for key, value in request_data.items():
            error = None

            if value is None:
                continue
            elif key in ["longitude", "id"]:
                # We skip these
                continue
            elif key == "related_to":
                status_code = self.relate_resources(resource_id, value)
            else:
                mapped_node = self.node_mapping[key]
                nodegroup_id = self.nodes[mapped_node]["nodegroup_id"]

                if nodegroup_id not in inserted_parents.keys() and key == "captureDate":
                    parent_id = self.get_parent_id(nodegroup_id, resource_id)

                    if parent_id:
                        # Set that we have attempted to insert this ID
                        inserted_parents[nodegroup_id] = parent_id
                        nodegroup_id = self.nodes[mapped_node]["graph_id"]
                        formatted_date = datetime.utcfromtimestamp(value)
                        value = formatted_date.strftime('%Y-%m-%d')
                        request_data[key] = value
                    else:
                        error = "Unable to get parent ID information"
                else:
                    parent_id = inserted_parents[nodegroup_id] if inserted_parents.get(nodegroup_id) else None

                if not error:
                    payload_contents = {
                        "tileid": "",
                        "data": {},
                        "nodegroup_id": nodegroup_id,
                        # Should be inside the loop?
                        "parenttile_id": parent_id,
                        "resourceinstance_id": resource_id, "sortorder": 0, "tiles": {}
                    }

                    # Get the key mapping
                    mapped_key = self.node_mapping[key]
                    # Now we add the payload data
                    self.add_payload_data(mapped_key, payload_contents, request_data)

                    payload = {
                        "data": json.dumps(payload_contents)
                    }

                    if key  == "url":
                        response = self.upload_image(value, payload)
                    else:
                        session = requests.Session()
                        endpoint = self.get_endpoint("tile")
                        response = session.post(endpoint, headers=self.get_headers(referrer=endpoint), data=payload)

                    try:
                        status_code = response.status_code
                    except AttributeError as e:
                        if type(response) == int:
                            status_code = response
                        else:
                            raise ValueError("Image report response has no status code.")
                else:
                    # We should just break the loop if error has been set
                    break

            # If any of these fail, we delete the resource and return the message
            if status_code != 200 or error:
                self.delete_resource(resource_id)

                final_error = error if error else response.content.decode('unicode_escape')

                self.logger.error(final_error)
                response_dict["message"] = f"Failed to insert {resource_id}."
                response_dict["status_code"] = status_code
                return response_dict

        # If no errors here, we can just go ahead and set status message/code and return
        response_dict["message"] = f"Success! for inserting {resource_id}"
        response_dict["status_code"] = 201
        return response_dict


    def delete_resource(self, resource_id):
        """
        Delete a specific resource based on a given ID.

        :param resource_id: The resource ID to delete on.
        :returns: result - The delete request response
        """

        endpoint = f"{self.get_endpoint('resource')}/{resource_id}"

        session = requests.Session()

        result = session.delete(endpoint, headers=self.get_headers(referrer=endpoint))

        if result.status_code != 200:
            self.logger.error(result.content.decode('unicode_escape'))

        return result
