import json
import requests

from django.conf import settings

# Authorisation tokens for the web/api
oauth_token = None  # Arches authorisation token
csrf_token = None  # The CSRF token
eamena_token = None  # Session token generated by the Django server
auth_token = None  # Session token

# The available endpoints we will be using
# TODO -  Fix consistency with slash endings
endpoints = {
    # Homepage - Used to request initial session token.
    "index": f"{settings.EAMENA_TARGET}/index.htm",
    # Used to generate the session token for access
    "log_in": f"{settings.EAMENA_TARGET}/auth/",
    # Generating/refreshing token for oauth-protected standard endpoints
    "oauth": f"{settings.EAMENA_TARGET}/o/token/",
    "resource": f"{settings.EAMENA_TARGET}/resource",
    "resources": f"{settings.EAMENA_TARGET}/resources",
    "add_resource": f"{settings.EAMENA_TARGET}/add-resource/",
    # Gets a specific resource based (resources/RESOURCE_TYPE/RESOURCE_ID - UUID)
    "get_resource": f"{settings.EAMENA_TARGET}/resources/%s/%s",  # Gets a specific resource
    "tile": f"{settings.EAMENA_TARGET}/tile",  # For interacting with tiles to insert data/retrieve IDs
    "search_resources": f"{settings.EAMENA_TARGET}/search/resources",
    "get_descriptors": f"{settings.EAMENA_TARGET}/resource/descriptors/"
}

# Mapping value names from AMAL -> EAMENA Arches values
node_mapping = {
    "captureDate": "DATE_OF_FILE",
    "url": "URL",
    "caption": "DESCRIPTION",
    "latitude": "SPATIAL_COORDINATES_GEOMETRY",
    "longitude": "SPATIAL_COORDINATES_GEOMETRY",
    "image": "FILE_UPLOAD"
}

# Mapping value names from EAMENA -> AMAL
rev_node_mapping = {
    "DATE_OF_FILE": "captureDate",
    "URL": "url",
    "DESCRIPTION": "caption",
    "FILE_UPLOAD": "image",
    "SPATIAL_COORDINATES_GEOMETRY": {"lat", "long"}
}

# Nodegroup IDs for insertion groups
nodegroups = {
    "imagery": "90181f02-5252-11ea-a3f7-02e7594ce0a0",
    "urls": "7f41dcde-518c-11ea-a3f7-02e7594ce0a0",
    "description": "b528b064-5189-11ea-a3f7-02e7594ce0a0",
    "location": "587447d5-b0c2-11ea-9b1f-02e7594ce0a0",
    "file_upload": "c712066a-8094-11ea-a6a6-02e7594ce0a0"
}

# Contains the graph_ids, nodegroup ID values, and the fstring/dict for payload formatting
nodes = {
    "DATE_OF_ACQUISITION": {
        "graph_id": "4077fb00-5253-11ea-a3f7-02e7594ce0a0",
        "nodegroup_id": nodegroups["imagery"],
        "payload": "%s"
    },
    "URL": {
        "graph_id": "7f41dcde-518c-11ea-a3f7-02e7594ce0a0",
        "nodegroup_id": nodegroups["urls"],
        "payload": {"en": {"direction": "ltr", "value": "%s"}}
    },
    "DESCRIPTION": {
        "graph_id": "b528b064-5189-11ea-a3f7-02e7594ce0a0",
        "nodegroup_id": nodegroups["description"],
        "payload": {
            "ar": {"direction": "rtl", "value": "%s"},
            "en": {"direction": "ltr", "value": "%s"},
        }
    },
    "DATE_OF_FILE": {
        "graph_id": "bf22c07c-52f1-11ea-a3f7-02e7594ce0a0",
        "nodegroup_id": nodegroups["imagery"],
        "payload": "%s"
    },
    "SPATIAL_COORDINATES_GEOMETRY": {
        "graph_id": "587447d2-b0c2-11ea-9b1f-02e7594ce0a0",
        "nodegroup_id": nodegroups["location"],
        "payload": {
            "type": "FeatureCollection",
            "features": [{
                "id": "f8498c82de3c3c3285ed4c24f050a48e",
                "type": "Feature",
                "properties": {
                    "nodeId": "587447d2-b0c2-11ea-9b1f-02e7594ce0a0"
                },
                "geometry": {
                    "coordinates": [],
                    "type": "Point"
                }
            }]
        }
    },
    "FILE_UPLOAD": {
        "graph_id": "c712066a-8094-11ea-a6a6-02e7594ce0a0",
        "nodegroup_id": nodegroups["file_upload"],
        "payload": [
            {
                "name": "%s",  # TODO - Requires Value?
                "accepted": True,
                "height": 0,  # TODO - Requires Value?
                "lastModified": 0,  # TODO - Requires Value?
                "size": 0,  # TODO - Requires Value?
                "status": "added",
                "type": "%s",  # TODO - Dealing with this?
                "width": 0,  # TODO - Requires Value?
                "url": None,
                "file_id": None,
                "index": 0,
                "content": ""            }
        ]
    }
}

# Graph ID values for EAMENA object types
graphs = {
    "Information Resource": "35b99cb7-379a-11ea-9989-06f597a7d5ce",
    "Built Component": "6c4f0703-c381-11ea-9026-02e7594ce0a0",
    "Detailed Condition Assessment": "f6235ff1-f992-11e9-b345-06f597a7d5ce",
    "Geoarchaeology": "5297fa9e-8e16-11ea-a6a6-02e7594ce0a0",
    "Grid Square": "77d18973-7428-11ea-b4d0-02e7594ce0a0",
    "Heritage Place": "34cfe98e-c2c0-11ea-9026-02e7594ce0a0",
    "Person-Organisation": "e98e1cee-c38b-11ea-9026-02e7594ce0a0"
}

def get_login_data():
    """
    Generates a dictionary containing relevant values used for site login.
    Contaisn the csrfmiddlewaretoken, account username and password.

    """
    data = {
        'csrfmiddlewaretoken': csrf_token,
        'username': settings.ARCHES_USERNAME,
        'password': settings.ARCHES_PASSWORD
    }
    return data

def get_headers(oauth=False, content_type=None):
    """
    Generates headers required to pass data to the Eamena instance.
    Used to insert the authentication data, etc.
    """
    headers = {
        'Origin': f'{settings.EAMENA_TARGET}',
        'Cookie': f'csrftoken={csrf_token}; eamena={eamena_token};'
    }

    if oauth:
        headers["Authorization"] = f"Bearer {auth_token}"

    if content_type:
        if content_type == "json":
            headers["Content-Type"] = "application/json"
        elif content_type == "form":
            headers["Content-Type"] = "multipart/form-data"
        else:
            # TODO - Error messaging etc.
            pass

    # TODO - A lof of these headers are possibly not useful.
    headers = {
        'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:139.0) Gecko/20100101 Firefox/139.0',
        'Accept': '*/*',
        'Accept-Language': 'en-GB,en;q=0.5',
        'Accept-Encoding': 'gzip, deflate',
        'Referer': 'http://10.249.103.187/resource/c279071a-051a-48c8-89df-c676a0ea9f26',
        'X-Requested-With': 'XMLHttpRequest',
        'Connection': 'keep-alive',
        'Origin': f'{settings.EAMENA_TARGET}',
        'Cookie': f'csrftoken={csrf_token}; eamena={eamena_token};',
        'X-CSRFToken': f'{csrf_token}',
        'Priority': 'u=0'
    }

    return headers


def get_oauth_token():
    """

    """
    data = {
        "username": settings.ARCHES_USERNAME,
        "password": settings.ARCHES_PASSWORD,
        "grant_type": "password",
        "settings.ARCHES_CLIENT_ID": settings.ARCHES_CLIENT_ID
    }
    response = requests.post(endpoints["oauth"], data=data).json()
    auth_token = response["access_token"]
    return response


def login(self):
    """
        Logs into the Eamena Arches instance.
        Requests the index page in order to generate a session and csrf token, which are
        saved in this object's variables.

        :returns response: The request's response object.
    """

    response = {
        "status": 0,
        "session": None
    }

    session = requests.Session()
    # Request the homepage to begin a session.
    session.get(endpoints["index"])

    # Set the Object's internal csrf token for later use
    csrf_token = session.cookies.get('csrftoken')

    # Get the pregenerated headers
    headers = get_headers()

    # Set the data payload to be sent, including csrf token, username and password
    login_data = get_login_data()

    login_request = requests.post(endpoints["log_in"], data=login_data, headers=headers)

    response["status"] = login_request.status_code
    request_cookies = login_request.request.headers["cookie"]

    # Determine the csrf and session (named eamena) token
    eamena_token = request_cookies.split("eamena=")[1]
    csrf_token = request_cookies.split("csrftoken=")[1].split(";")[0]

    self.eamena_token = eamena_token
    self.csrf_token = csrf_token
    # TODO - Should really be just returning some kind of error message instead!
    return response

def search_resources(request):
    """

    :param request: The request object containing coordinate data
    :returns: A dict containing the status code and any hits
    """

    coordinates = json.loads(request.body)["coordinates"][0]
    url = settings.EAMENA_TARGET + "/search/resources"
    map_filter = {
        "type": "FeatureCollection",
        "features": [
            {
                "type": "Feature",
                "geometry": {
                    "coordinates": [
                        coordinates
                    ],
                    "type": "Polygon" if len(coordinates) > 1 else "Point"
                }
            }
        ]
    }
    url += "?map-filter=" + json.dumps(map_filter)
    heritage_page = "34cfe98e-c2c0-11ea-9026-02e7594ce0a0"
    resource_filter = f"""&resource-type-filter=[{{"graphid":"{heritage_page}","name":"Information Resource","inverted":false}}]"""
    url += resource_filter

    response = requests.get(url)
    result_json = json.loads(response.text)
    result_hits = result_json["results"]["hits"]["hits"]

    response_hits = []
    for hit in result_hits:
        hit_id = hit["_id"]
        hit_data = hit["_source"]
        hit_coords = hit_data["points"][0]["point"]

        # displaydescription is actually mapped to Resource Summary->Name in Eamena.
        hit_dict = {
                "resource_id": hit_id,
                "resource_name": hit_data["displayname"],
                "resource_type": "PLACEHOLDER", # What should this actually say for Heritage Place
                "resource_description": hit_data["displaydescription"],
                "geometry": {"coordinates": [hit_coords["lat"], hit_coords["lon"]]}
        }

        response_hits.append(hit_dict)

    return {
        "status_code": response.status_code if response.status_code else 500,
        "hits": response_hits
    }
